# Workflow for continuous deployment to linode server

name: CD

# Controls when the action will run. Triggers the workflow on push request #
# events but only for the master branch.
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment: main
    
    env:
       API_USER_NAME: ${{ secrets.API_USER_NAME }}
       APP_API_URL: ${{ vars.APP_API_URL }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out entier repository
      - uses: actions/checkout@v2

      # Push to our linode server
      - name: Push to server
        # uses: appleboy/ssh-action@master # changed to version 0.1.4
           
        run: echo "API_USER_NAME is $API_USER_NAME and APP_API_URL is $APP_API_URL"
