name: Secrets and Environment Variables

on:
  workflow_dispatch

jobs:
  top-secret-main:
    runs-on: ubuntu-latest
    environment: main
    env:
      API_USER_NAME: ${{ secrets.API_USER_NAME }}

    steps:
      - name: Read a variable
        run: echo "My API_USER_NAME value in the production job is $API_USER_NAME"
